//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FermaksanEntities : DbContext
    {
        public FermaksanEntities()
            : base("name=FermaksanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<anamenu> anamenu { get; set; }
        public virtual DbSet<cms> cms { get; set; }
        public virtual DbSet<iletisim> iletisim { get; set; }
        public virtual DbSet<k2m> k2m { get; set; }
        public virtual DbSet<kategoriler> kategoriler { get; set; }
        public virtual DbSet<makinefotograflar> makinefotograflar { get; set; }
        public virtual DbSet<makineler> makineler { get; set; }
        public virtual DbSet<mansetler> mansetler { get; set; }
        public virtual DbSet<s2m> s2m { get; set; }
        public virtual DbSet<sabitler> sabitler { get; set; }
        public virtual DbSet<sektorler> sektorler { get; set; }
        public virtual DbSet<servis> servis { get; set; }
    }
}
